version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    command: gunicorn vacstage.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  selenium:
    image: selenium/standalone-firefox
    ports:
    - 4444:4444
volumes:
  postgres_data:
  media_volume: